spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: liquibase/db.changelog.yaml
    enabled: true
  main:
    allow-circular-references: true

token:
  secret: ${SECRET_TOKEN}

server:
  port: 8081
